### PR TITLE
Migrate to fsproj

### PR DESCRIPTION
**Pull request by slang25**
Updated some packages too. Leaving framework at 1.0, as I don't know if AWS supports it yet. This is inline with the RC4 tooling, `fsproj` is not supported by Visual Studio 2017 and won't be in the first RTM, will likely come in the first update.

### CODE REVIEW

**Comment by lukemerrett** [comment]
Cheers for this @slang25, I've tested locally using the dotnet command line tooling version `1.0.0-preview2-1-003177`, unfortunately it throws the below error:

```
Couldn't find 'project.json' in current directory
```

I'm not seeing an updated dotnet core SDK that supports .fsproj, is this exclusive to the VS 2017 RC, or does it require this RC package here? https://github.com/dotnet/core/blob/master/release-notes/rc4-download.md

**Comment by slang25** [comment]
Hey, yeah you'll need the RC4 SDK, the commands are the same. Note that if you then want to with with project.json then you need a global.json file to force the SDK version

**Comment by slang25** [comment]
Another thing to remember is that vs2017 won't have support for dotnet core fsproj projects when it RTMs, this will hopefully come in a vs update.

**Comment by slang25** [comment]
@lukemerrett Updated to new tooling "proper". VS Code + Ionide required.

**Pull request merged**
