### PR TITLE
remove dev feeds (unused) and restrict dotnet-compile-fsc version

### PR DESCRIPTION
**Pull request by enricosada**

### CODE REVIEW

**Comment by lukemerrett** [comment]
Cheers for the PR @enricosada; I'll load it locally this weekend and test it out.  What is the reason for removing the `nuget.config` file?  My understanding is it's good practise to be explicit about package sources at project level, unless there's been a change to the core sdk?

**Comment by enricosada** [comment]
@lukemerrett all the packages required (aspnet, dotnet, fsharp) are published on nuget.org.
That's the default feed (when `nuget.config` doesnt exists), so no need to add it.
I think is useless to explicit write that, and use nuget.config when there are dev/specific feeds only.

The main issue is some of previous feeds were dev feed and that can be an issue at restore time, with newer/incompatbile packages resolved.

If you want to specify feed with a nuget.config, you need to add `<clear />` before the feeds, otherwise feed are just added to global config.

The pin to `1.0.0-preview2-*` it's because that's the version of `dotnet-compile-fsc` aligned with preview2.
I dont think there is going to be a preview2.1 now, but just to be sure.

**Comment by lukemerrett** [comment]
## Test Log 

- [x] AWS Lambda project builds successfully on existing local setup
- [x] Serverless project builds successfully on existing local setup
- [x] Serverless project deploys successfully on existing local setup
- [x] AWS Lambda project builds successfully on fresh Windows VM
- [x] Generated package works as expected on AWS Lambda

**Comment by lukemerrett** [comment]
@enricosada cheers Enrico, tested it out and happy it's working, merged.

**Pull request merged**
