### PR TITLE
added netstandard 2.0 dotnet template

### PR DESCRIPTION
**Pull request by richardjharding**
Hi Luke - was looking at this myself and as the aws templates don't yet support F# thought I'd update yours to create a dotnet template

root project file now is now just the template - so dotnet pack that to create a template nuget

README still needs updating and I've left the serverless folder alone as I've not used that tool before

Hope its useful - let me know if you want me to tweak it - I've not published the resulting nuget  - just used locally  - let me know if you do publish

Cheers
Rich

#6

### CODE REVIEW

**Comment by whitetigle** [comment]
+1 :)

**Comment by lukemerrett** [comment]
@richardjharding thank you for the PR, sorry for the late response, only just got back from travelling.

I'll clone this today and do a quick sanity check before merging

**Comment by richardjharding** [comment]
no worries - sounded like an awesome trip!

**Comment by lukemerrett** [comment]
Merging into a separate branch so I can update the readme before hitting master

**Comment by whitetigle** [comment]
Hi there, meanwhile just so you know I added paket, serverless support and netcore2 [there](https://github.com/whitetigle/aws-lambda-serverless-fsharp). 

Maybe we could join forces on this part?

**Comment by lukemerrett** [comment]
@whitetigle It would certainly be helpful to get a second pair of eyes on the updates, and suggestions for the serverless migration.

I'll raise a PR back into master when I'm finished so we can discuss

**Comment by whitetigle** [comment]
ok!

**Pull request merged**
